/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopesquisaordenacao;

import javax.swing.JOptionPane;
import trabalhopesquisaordenacao.Arquivo;

/**
 *
 * @author matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    int [] dados;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnCarregarArquivo = new javax.swing.JButton();
        txtTotalNumeros = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        RbBubble = new javax.swing.JRadioButton();
        RbInsertion = new javax.swing.JRadioButton();
        RbSelection = new javax.swing.JRadioButton();
        RbQuick = new javax.swing.JRadioButton();
        RbComb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnExecultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnGeradorNumeros = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarregarArquivo.setText("Carregar");
        btnCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarArquivoActionPerformed(evt);
            }
        });

        txtTotalNumeros.setEditable(false);

        jLabel1.setText("Total de números:");

        btnGroup.add(RbBubble);
        RbBubble.setText("Bubble");

        btnGroup.add(RbInsertion);
        RbInsertion.setText("Insertion");

        btnGroup.add(RbSelection);
        RbSelection.setText("Selection");

        btnGroup.add(RbQuick);
        RbQuick.setText("QuickSort");

        btnGroup.add(RbComb);
        RbComb.setText("CombSort");

        jLabel2.setFont(new java.awt.Font("C059", 1, 16)); // NOI18N
        jLabel2.setText("Benchmark");

        btnExecultar.setText("Execultar");
        btnExecultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecultarActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnGeradorNumeros.setText("Gerar números");
        btnGeradorNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeradorNumerosActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RbBubble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbInsertion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbSelection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbQuick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbComb)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(txtTotalNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCarregarArquivo))
                            .addComponent(btnGeradorNumeros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addComponent(btnExecultar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarArquivo)
                    .addComponent(txtTotalNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnExecultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnGeradorNumeros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbBubble)
                    .addComponent(RbInsertion)
                    .addComponent(RbSelection)
                    .addComponent(RbQuick)
                    .addComponent(RbComb))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarArquivoActionPerformed
                                               
        try{
        String nomeArquivo = JOptionPane.showInputDialog("Informe o nome do arquivo:");
        Arquivo arq = new Arquivo(nomeArquivo);
        dados = arq.lerNumeros();
        txtTotalNumeros.setText(String.valueOf(dados.length));
        JOptionPane.showMessageDialog(null, "Arquivo carregado com sucesso!");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar o arquivo!" +e.getMessage());
        }
                                 
    }//GEN-LAST:event_btnCarregarArquivoActionPerformed

    private void btnGeradorNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeradorNumerosActionPerformed
       try {
            // Solicitar nome do arquivo
            String nomeArquivo = JOptionPane.showInputDialog("Informe o nome do arquivo:");
            if (nomeArquivo == null || nomeArquivo.trim().isEmpty()) {
                return;
            }
            
            // Solicita a quantidade de numeros 
            String quantidadeStr = JOptionPane.showInputDialog("Quantidade de números para gerar:");
            if (quantidadeStr == null || quantidadeStr.trim().isEmpty()) {
                return;
            }
            
            int quantidade;
            try {
                quantidade = Integer.parseInt(quantidadeStr);
                if (quantidade <= 0) {
                    JOptionPane.showMessageDialog(null, "A quantidade deve ser maior que zero!");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Quantidade inválida! Digite um número válido.");
                return;
            }
            
            // Solicitar valor máximo
            String valorMaximoStr = JOptionPane.showInputDialog("Valor máximo dos números:");
            if (valorMaximoStr == null || valorMaximoStr.trim().isEmpty()) {
                return;
            }
            
            int valorMaximo;
            try {
                valorMaximo = Integer.parseInt(valorMaximoStr);
                if (valorMaximo <= 0) {
                    JOptionPane.showMessageDialog(null, "O valor máximo deve ser maior que zero!");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor máximo inválido! Digite um número válido.");
                return;
            }
            
            // Gerar os números
            Arquivo arq = new Arquivo(nomeArquivo.trim());
            arq.gerarNumerosAleatorios(quantidade, valorMaximo);
            
            JOptionPane.showMessageDialog(null, 
                "Arquivo gerado com sucesso!\n" +
                "Nome: " + nomeArquivo + "\n" +
                "Quantidade: " + quantidade + " números\n" +
                "Valor máximo: " + valorMaximo + "\n\n");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar números: " + e.getMessage());
        }                 
   
    }//GEN-LAST:event_btnGeradorNumerosActionPerformed

    private void btnExecultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecultarActionPerformed
      if (dados == null || dados.length == 0) {
        JOptionPane.showMessageDialog(this, "Carregue um arquivo primeiro!");
        return;
    }

    // Verificar qual método foi selecionado
    String metodo = "";
    if (RbBubble.isSelected()) metodo = "Bubble Sort";
    else if (RbInsertion.isSelected()) metodo = "Insertion Sort";
    else if (RbSelection.isSelected()) metodo = "Selection Sort";
    else if (RbQuick.isSelected()) metodo = "Quick Sort"; 
    else if (RbComb.isSelected()) metodo = "Comb Sort";
    else {
        JOptionPane.showMessageDialog(this, "Selecione um método de ordenação!");
        return;
    }

    try {
        // Limpar resultado anterior
        txtResultado.setText("Limpando...");
        
        //Clonando
        int[] copia = dados.clone();

        // Medir o tempo de execução
        long inicio = System.currentTimeMillis();

        // Executar o método selecionado
        switch (metodo) {
            case "Bubble Sort": 
                Metodos.bubbleSort(copia); 
                break;
            case "Insertion Sort": 
                Metodos.insertionSort(copia); 
                break;
            case "Selection Sort": 
                Metodos.selectionSort(copia); 
                break;
            case "Quick Sort": 
                Metodos.quickSort(copia, 0, copia.length - 1); 
                break;
            case "Comb Sort": 
                Metodos.combSort(copia); 
                break;
        }

        long fim = System.currentTimeMillis();
        long tempo = fim - inicio;

        // Mostrar resultados
        String resultado = "Método: " + metodo + "\n";
        resultado += "Tempo: " + tempo + " ms\n";
        resultado += "Elementos: " + copia.length + "\n\n";
        resultado += "Primeiros 10 números:\n";

        for (int i = 0; i < Math.min(10, copia.length); i++) {
            resultado += copia[i] + " ";
        }

        txtResultado.setText(resultado);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro na ordenação: " + e.getMessage());
    }  
                                        
    
    }//GEN-LAST:event_btnExecultarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Limpar
        txtResultado.setText("");
        JOptionPane.showMessageDialog(this, "Resultado limpo!");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbBubble;
    private javax.swing.JRadioButton RbComb;
    private javax.swing.JRadioButton RbInsertion;
    private javax.swing.JRadioButton RbQuick;
    private javax.swing.JRadioButton RbSelection;
    private javax.swing.JButton btnCarregarArquivo;
    private javax.swing.JButton btnExecultar;
    private javax.swing.JButton btnGeradorNumeros;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtTotalNumeros;
    // End of variables declaration//GEN-END:variables
}
